version: '3.9'

volumes:
  postgres_data:

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"


  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data://var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
