"""Init and add 2 models, mushroom and basket

Revision ID: 089fcbdb4fd8
Revises: 
Create Date: 2025-05-19 05:19:59.211288

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '089fcbdb4fd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mushrooms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_edible', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_fresh', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mushroombaskets',
    sa.Column('mushroom_id', sa.UUID(), nullable=False),
    sa.Column('basket_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mushroom_id'], ['mushrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mushroom_id', 'basket_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mushroombaskets')
    op.drop_table('mushrooms')
    op.drop_table('baskets')
    # ### end Alembic commands ###
